# Generated by Django 4.0.4 on 2022-05-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviasatuu', '0002_flight_aviacompany_flight_price_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='price',
            new_name='price_for_adult',
        ),
        migrations.AddField(
            model_name='flight',
            name='price_for_child',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passenger',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
