# Generated by Django 4.0.4 on 2022-05-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviasatuu', '0003_rename_price_flight_price_for_adult_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='price_for_adult',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='price_for_child',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='price',
        ),
    ]
