# Generated by Django 4.0.4 on 2022-05-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
