# Generated by Django 4.0.4 on 2022-05-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_coutry_apartment_country_apartment_bath_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='photo',
            field=models.ImageField(null=True, upload_to='apartments/'),
        ),
    ]
