# Generated by Django 4.0.4 on 2022-05-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erkindik', '0002_art_description_art_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='image',
            field=models.ImageField(null=True, upload_to='arts/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
